Adding Issue Template
ROCm/composable_kernel pull request #1094
Opened 2023-12-08 16:10 UTC by abhimeda

Hello, this PR is introducing a new issue template for ROCm public repositories to make it easier for users to submit the details for issues and bugs. Problems pertaining to documentation or non-bug related, users have the ability to open a blank issue template to submit their report. 

Thank you,
Community Support Team (ML SW SDK)

2023-12-08 17:56 UTC, samjwu commented on .github/ISSUE_TEMPLATE/issue_report.yml
> +        -  amdgpu KCL/autoconf
small typo: an extra space

2023-12-11 21:50 UTC, samjwu requested changes
Can you add MI300 as an option?

2023-12-15 01:05 UTC, illsilin submitted a review, later dismissed

2023-12-15 01:11 UTC, illsilin commented
I think the list of architectures is probably not very suitable for CK. 
We only support MI100/200/300, and Navi3x. 
So we need to add the MI300 and Navi3x, and delete the rest.

2023-12-15 17:29 UTC, illsilin commented
I've added the MI300 architectures and also the rocm 5.6.1 and 6.0.0 versions, since 6.0 is about to be released any day now.

2023-12-15 17:29 UTC, illsilin approved these changes

2023-12-15 17:40 UTC, samjwu approved these changes

2023-12-15 17:41 UTC, merged