Pool2d max/avg kernel in the BWD version
ROCm/composable_kernel pull request #1494
Opened 2024-08-30 08:00 UTC by mozga-amd

The pull request contains changes related to the pool2d max/avg operator in the BWD version for the types I8, F8, F32, BF16, and F16.

2024-09-06 13:32 UTC, aosewski requested changes
Good work, however there are few things to reconsider or fix.  General note plase make sure that the naming formatting convention is coherent in function variable names. I saw often mixed variables w/wo `_` underscores.

2024-09-06 13:32 UTC, aosewski commented on include/ck/utility/reduction_operator.hpp
> +                          is_same<T, f8_t>::value || is_same<T, int8_t>::value,
You don't have to check for `f8_t` here since you provide specialization for this type. 
```suggestion
                          is_same<T, int8_t>::value,
```

2024-09-06 13:32 UTC, aosewski commented on include/ck/tensor_operation/gpu/device/impl/device_avgpool2d_bwd_nhwc_nhwc.hpp
> +            throw std::runtime_error("dimension is incorrect - a1");
Please make this error more user friendly.

2024-09-06 13:32 UTC, aosewski commented on include/ck/tensor_operation/gpu/device/impl/device_avgpool2d_bwd_nhwc_nhwc.hpp
> +            throw std::runtime_error("dimension is incorrect - s1");
Please make this error more user friendly.

2024-09-06 13:32 UTC, aosewski commented on include/ck/tensor_operation/gpu/device/impl/device_avgpool2d_bwd_nhwc_nhwc.hpp
> +    static bool IsSupportedArgument(const Argument& arg)
You may add here checks to disable failing fp8 instances based on input tensor sizes.

2024-09-06 13:32 UTC, aosewski commented on library/include/ck/library/tensor_operation_instance/gpu/max_pool_bwd.hpp
> +#pragma once
We usually put this `pragma` at the very beginning of the file.

2024-09-06 13:32 UTC, aosewski commented on library/src/tensor_operation_instance/gpu/avg_pool2d_bwd/device_avg_pool2d_bwd_nhwc_f8_instance.cpp
> +    add_device_operation_instances(instances, device_avgpool_2D_bwd_nhwc_instances<F8, F8, F8>{});
Maybe we should use here the `ComputeType` as at least twice as f8, that is F16? or rather F32? Otherwise you could easily get overflow when reducing data.

2024-09-06 13:32 UTC, aosewski commented on library/src/tensor_operation_instance/gpu/avg_pool2d_bwd/device_avg_pool2d_bwd_nhwc_int8_instance.cpp
> +    add_device_operation_instances(instances, device_avgpool_2D_bwd_nhwc_instances<I8, I8, I8>{});
Maybe we should use here the `ComputeType` as wider data type as i8, ie i32? Otherwise you could easily get overflow when reducing data.

2024-09-06 13:32 UTC, aosewski commented on library/src/tensor_operation_instance/gpu/max_pool_bwd/CMakeLists.txt
> +					 device_max_pool_bwd_int8_instance.cpp)
Please fix identation.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_avg_pool2d_bwd_impl.hpp
> +    ck::index_t N_, ck::index_t C_, ck::index_t H, ck::index_t W, TensorLayout layout)
The arguments naming convention is not coherent. Please remove underscores.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_avg_pool2d_bwd_impl.hpp
> +                return false;
Please do not return verification result so quickly. Let it iterate through all instances, report their verification status and in the end return overall verification status.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_max_pool2d_bwd_impl.hpp
> +// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.
```suggestion
// Copyright (c) 2024, Advanced Micro Devices, Inc. All rights reserved.
```

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_avg_pool2d_bwd_impl.hpp
> +#include "ck/library/tensor_operation_instance/gpu/pool3d_fwd.hpp"
I don't see you use pool3d_fwd here. Please remove this header.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_max_pool2d_bwd_impl.hpp
> +            if(time_kernel)
This check is rather not needed here. Let's log both for timing and verification mode this message. Please do the same for avg.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_max_pool2d_bwd_impl.hpp
> +                return false;
Similarly as for avg. Please do not return so quickly. Let it iterate through all instances and verify them and only after that return the overall verification status.

2024-09-06 13:32 UTC, aosewski commented on profiler/src/profile_avg_pool2d_bwd.cpp
> +    std::cout << "arg1: data type (0: fp16; 1: fp32; 5: bf16)\n"
Please update supported data types.

2024-09-06 13:32 UTC, aosewski commented on profiler/include/profiler/profile_avg_pool2d_bwd_impl.hpp
> +          typename ComputeDataType,
If we do not use it, lets remove this tparam.

2024-09-06 13:32 UTC, aosewski commented on profiler/src/profile_avg_pool2d_bwd.cpp
> +        ck::profiler::profile_avg_pool2d_bwd_impl<F16, F16, F16, NHWC, NHWC>(do_verification,
If we do not use this third data type (`ComputeDataType`) then please remove it in order to not make confusion.

2024-09-06 13:32 UTC, aosewski commented on profiler/src/profile_max_pool2d_bwd.cpp
> +    std::cout << "arg1: data type (0: fp16; 1: fp32; 5: bf16)\n"
Please update supported data types.

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +class AvgPool2DB_bf16 : public AvgPool2dBWDTest<TType>
```suggestion
class AvgPool2D_bf16 : public AvgPool2dBWDTest<TType>
```

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +class AvgPool2DB_f8 : public AvgPool2dBWDTest<TType>
```suggestion
class AvgPool2D_f8 : public AvgPool2dBWDTest<TType>
```

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +    // trigger Run()
This comment does not give any valuable information. Please remove it here and below.

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +using Avg_Pool_2D_f8_float_Types   = ::testing::Types<std::tuple<F8, F8, F8>>;
Please always do computation (here reduction in wider range data type, to prevent overflow)
Maybe that was the bug? 
```suggestion
using Avg_Pool_2D_f8_float_Types   = ::testing::Types<std::tuple<F8, F8, F32>>;
```

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +using Avg_Pool_2D_f8_float_Types   = ::testing::Types<std::tuple<F8, F8, F8>>;
I wonder if this would compile if you will enable only one data type ie fp16 through `CK_ENABLE_FP16` cmake flag?

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +using Max_Pool_2D_f8_float_Types   = ::testing::Types<std::tuple<F8, F8, I32>>;
Why `float_Types` ? What `float` means here? Please also make the naming convention coherent with above aliases.

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +TYPED_TEST_SUITE(MaxPool2DB_bf16, Max_Pool_2D_bf16_float_Types);
```suggestion
TYPED_TEST_SUITE(MaxPool2D_bf16, Max_Pool_2D_bf16_float_Types);
```

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +TYPED_TEST_SUITE(MaxPool2DB_f8, Max_Pool_2D_f8_float_Types);
```suggestion
TYPED_TEST_SUITE(MaxPool2D_f8, Max_Pool_2D_f8_float_Types);
```

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +    // trigger Run()
As in avg.

2024-09-06 13:32 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +TYPED_TEST(MaxPool2DB_f8, MaxPool2DBTest_f8)
Does it not work for MAX either ? Please check if the `AtomicAdd` may be a problem here.

2024-09-06 14:43 UTC, mozga-amd commented on test/pool/test_max_pool2d_bwd.cpp
> +using Max_Pool_2D_f8_float_Types   = ::testing::Types<std::tuple<F8, F8, I32>>;
Good catch. Should be `_bitint_types`

2024-09-11 13:03 UTC, aosewski requested changes

2024-09-11 13:03 UTC, aosewski commented on include/ck/utility/reduction_operator.hpp
> +
Why you need this one ? The int8_t is a standard c++ type.

2024-09-11 13:03 UTC, aosewski commented on library/src/tensor_operation_instance/gpu/avg_pool2d_bwd/device_avg_pool2d_bwd_nhwc_int8_instance.cpp
> +    add_device_operation_instances(instances, device_avgpool_2D_bwd_nhwc_instances<I8, I8, F32>{});
Shouldn't compute data type be integer? 
```suggestion
    add_device_operation_instances(instances, device_avgpool_2D_bwd_nhwc_instances<I8, I8, I32>{});
```

2024-09-11 13:03 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +using Avg_Pool_2D_f8_bitint_types  = ::testing::Types<std::tuple<F8, F8>>;
```suggestion
using Avg_Pool_2D_bf16_types = ::testing::Types<std::tuple<BF16, BF16>>;
using Avg_Pool_2D_f8_types  = ::testing::Types<std::tuple<F8, F8>>;
```

2024-09-11 13:03 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
>      // trigger Run()
All those comments `// trigger Run()` doesn't make the code more clear, so please remove them.

2024-09-11 13:03 UTC, aosewski commented on test/pool/test_max_pool2d_bwd.cpp
> +        }
That's a nice idea!

2024-09-11 13:03 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> -    {{2, 32, 30, 30}, {2, 2}, {2, 2}, {1, 1}, {1, 1}, {1, 1}}};
Why you have removed those test cases?  Are they passing? I think we need also test case with bigger C dimension.

2024-09-11 13:03 UTC, aosewski commented on test/pool/test_avg_pool2d_bwd.cpp
> +                    1,
Please change it to floating point data type initialization.

2024-09-12 09:47 UTC, aosewski approved these changes

2024-09-12 09:47 UTC, merged