add int8 gemm multiply multiply a8w8
ROCm/composable_kernel pull request #1591
Opened 2024-10-21 14:01 UTC by valarLip

add int8 gemm a8w8 fused dequant

2024-10-22 06:23 UTC, aska-0096 requested changes
Please pull the develop branch.

2024-10-22 06:23 UTC, aska-0096 commented on profiler/fp8_gmm_profiler.sh
> +EXE="$(find . -name ckProfiler -type f | head -n 1)"
please remove this file

2024-10-22 06:23 UTC, aska-0096 commented on profiler/int8_gmm_profiler.sh
> +EXE="$(find . -name ckProfiler -type f | head -n 1)"
please remove this file

2024-10-22 15:11 UTC, spolifroni-amd submitted a review, later dismissed
Nothing changed that affects docs.

2024-10-23 03:30 UTC, aska-0096 approved these changes, later dismissed
LGTM. We can merge it once CI pass.

2024-10-25 06:37 UTC, carlushuang approved these changes
LGTM

2024-10-26 08:39 UTC, merged