topk_softmax
ROCm/composable_kernel pull request #1592
Opened 2024-10-22 02:04 UTC by carlushuang

2024-10-24 13:11 UTC, aosewski requested changes
A looot of code, thus just finished on `block_reduce.hpp` file. A lot of interesting changes. However we can't keep the code undocumented like it is right now, since it becomes more and more confusing and hard to understand. This won't attract developers to write kernels in CK-Tile level API.  Please add comments at least to the changes to you made to tile-level API.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/README.md
> +This folder contains example for topk-softmax kernel using ck_tile tile-programming implementation. This kernel is often used in Moe model, before launching the fused-moe-gemm block. The input is a `
```suggestion
This folder contains example for topk-softmax kernel using ck_tile tile-programming implementation. This kernel is often used in Moe model, before launching the fused-moe-gemm block. The input is a `token*expert` 2d matrix. The op will do a softmax per row(`expert`), then find the `topk` value for each row. Output is a `token*topk`  weight(usually fp32) and index(int32) 2d tensor.
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/script/smoke_test.sh
Why we are not using google unit tests in CK-Tile?

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/README.md
> +      -kname    t to 1 will print kernel name (default:0)
```suggestion
      -kname    when set to 1 it will print kernel name (default:0)
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.
```suggestion
// Copyright (c) 2024, Advanced Micro Devices, Inc. All rights reserved.
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    assert(len.size() == 2);
This line is a no-op in a release build mode. If you want to check it maybe throw an error when this condition fails?

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +                auto v = ck_tile::type_convert<float>(x(std::vector<std::size_t>{i, j}));
It should also work in this way:
```suggestion
                auto v = ck_tile::type_convert<float>(x(i, j)));
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +                std::cout << x(std::vector<std::size_t>{i, j}) << " ";
```suggestion
                std::cout << x(i, j) << " ";
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    // dump_host_tensor_2d(x);
Leftover code.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    // dump_host_tensor_2d(y);
Leftover code.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +}
Why not moving this to `check_err.hpp` file? Or is this op specific?

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +        .insert("kname", "0", "t to 1 will print kernel name");
```suggestion
        .insert("kname", "0", "when set to 1, it will print kernel name");
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    assert(stride_output >= topk);
Please throw an error when those condition do not hold. `assert` is a no-op in release mode.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    // int repeat = args.get_int("repeat");
Commented leftover code. Please remove if not needed.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +        printf("topk:%d should smaller than (or equal to) experts:%d\n", topk, experts);
Additionally why not using c++ `std::cout` ?
```suggestion
        printf("topk:%d value should be smaller than, or equal to number of experts:%d\n", topk, experts);
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    ck_tile::HostTensor<InputType> x_host({tokens, experts}, {stride_input, 1});
What about renaming this to `in_host` ? - would be much more clear that this is input data.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    }();
Can't we just use brace list initializer? for `topk_softmax_trait` data type? This looks confusing.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    // ck_tile::stream_config sc{nullptr};
Leftover.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    printf("[%s|%s]tokens:%d, experts:%d, topk:%d, st_i:%d, st_o:%d, ms:%f, ",
Why not using c++ `std::cout` ?

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    fflush(stdout);
```suggestion
    std::cout << std::endl;
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +        ck_tile::HostTensor<WeightType> value_ref({tokens, topk}, {stride_output, 1});
This comment is confusing, since you actually  pass strides.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +        // auto [value_ref, index_ref] =
Leftover.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax_api.cpp
> +        }
Please add `else` branch to cover case when `t.experts > 192`

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax_api.cpp
> +        }
Please add `else` branch to cover case when `t.experts > 192`

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax_api.cpp
No copyright notice.

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/09_topk_softmax/topk_softmax_api.hpp
> +// Copyright (c) 2018-2023, Advanced Micro Devices, Inc. All rights reserved.
```suggestion
// Copyright (c) 2024, Advanced Micro Devices, Inc. All rights reserved.
```

2024-10-24 13:11 UTC, aosewski commented on example/ck_tile/CMakeLists.txt
> +add_subdirectory(09_topk_softmax)
```suggestion
add_subdirectory(06_topk_softmax)
```

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/algorithm/space_filling_curve.hpp
Please update year in copyright notice.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/algorithm/space_filling_curve.hpp
> +    // FIXME: return tuple of number<>, which is compile time only variable
Isn't it fixed already?  
Ohh... it took me a moment to catch-up what's going on here. The naming is really confusing here. I'd rather keep it as it was - at least it added clear message. And the comment to the function should be kept - ofcourse without `FIXME:`.
Or what about `get_tuple_of_number_with_index` ? It's long, but at least clear.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/algorithm/space_filling_curve.hpp
> +
Why messing and duplicating code with all those `_static` functions ?  Why not just calling proper `get_index` (which should return in compile time tuple of numbers) in `get_forward_step` ?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/arch/amd_buffer_addressing.hpp
> +                                              // uint32_t*>(reinterpret_cast<uintptr_t>(smem)),
Is this comment needed here or it's leftover?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/arch/amd_buffer_addressing.hpp
> +                                        smem, // reinterpret_cast<CK_TILE_LDS_ADDR
Is this comment needed here or it's leftover?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/numeric/math.hpp
Please remove all the code you disabled with `if 0`

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/buffer_view.hpp
> +                                      bool_constant<oob_conditional_check> = {}) const
Please add documentation to this function. When adding this additional `linear_offset` parameter it all starts to be confusing what each parameters referes to...

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/buffer_view.hpp
> +                                      bool_constant<oob_conditional_check> = {}) const
As above.... please add documentation

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/buffer_view.hpp
> +                                          index_t i_offset,
Please add documentation - to what corresponds those parameters?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/buffer_view.hpp
> +#endif
Leftover code ? Is it needed?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/buffer_view.hpp
Please add documentation to the functions what it is `linear_offset` cause this code is making more and more confusing and nobody would understand it by just reading it....

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/load_tile.hpp
> +CK_TILE_DEVICE auto load_tile(const tile_window_linear<BottomTensorView_,
Could you please add some comment when this overload is useful, or why it uses `tile_window_linear` ? It is CK-Tile API, so it would be good to have here some documentation, at least for developers to make less confusions.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +        const ATopIndex& idx_diff_adaptor_top) const
This change makes the code more confusing.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +// Note: this tile window do not support single issue
What do you mean by `single issue` ?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +    CK_TILE_DEVICE auto load(number<i_access_unsupport_>          = {},
Please add documentation. What does it referes to this new paramter `i_access_unsuport_ `?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +              index_t i_access_unsupport_ = -1,
Please add documentation.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +                    0 /**/,
What is this zero ? Empty comment....

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +              index_t i_access_unsupport_ = -1,
I don't see you use this template variable in this function... is it needed ??? What is is used for?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +    template <index_t i_access_unsupport_ = -1, bool oob_conditional_check = true>
Same here....

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/core/tensor/tile_window.hpp
> +// this version must not be called under a constexpr context
```suggestion
// this version can't be called in a constexpr context
```

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/host/fill.hpp
> +    std::mt19937 gen_{}; // (seed_.has_value() ? *seed_ : std::random_device{}());
Leftover comment ?

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/host/reference/reference_softmax.hpp
> +    assert(dim == -1 || dim < rank);
Asserts are no-op in release builds.

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/host/reference/reference_topk.hpp
> +// Copyright (c) 2018-2023, Advanced Micro Devices, Inc. All rights reserved.
```suggestion
// Copyright (c) 2024, Advanced Micro Devices, Inc. All rights reserved.
```

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/ops/elementwise.hpp
> +// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.
Year

2024-10-24 13:11 UTC, aosewski commented on include/ck_tile/ops/elementwise/unary_element_wise_operation.hpp
> +// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.
```suggestion
// Copyright (c) 2024, Advanced Micro Devices, Inc. All rights reserved.
```

2024-10-24 13:30 UTC, carlushuang commented on example/ck_tile/09_topk_softmax/script/smoke_test.sh
ck_tile example would want to keep this as simple as possible, and potentially introduce codegen to example, so well not use google unit test

2024-10-25 07:33 UTC, aosewski commented on example/ck_tile/09_topk_softmax/script/smoke_test.sh
It starts to look like the examples becomes an entire library on its own.. I don't think this is a good solution. If we want to keep examples as simple as possible we should stop adding dependencies on them. Right now our examples are our host API, they become to be generator of instances and even whole tests at the same time.... Unit tests have a lot of advantages, they're meant to be simple with clear error messages and structure. If sth fails running such script it will hide in the output log. Using unit-test you at least get clear summary with clear information what passed and what not.

2024-10-25 14:24 UTC, aosewski submitted a review, later dismissed
Don't want to block PR, but need more time to go through.

2024-10-26 03:29 UTC, carlushuang commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +}
op specific...

2024-10-26 04:12 UTC, carlushuang commented on include/ck_tile/core/tensor/load_tile.hpp
> +CK_TILE_DEVICE auto load_tile(const tile_window_linear<BottomTensorView_,
I add many comment in the `tlie_window_linear` struct design, so need check into that file

2024-10-26 04:14 UTC, carlushuang commented on include/ck_tile/core/tensor/tile_window.hpp
> +        const ATopIndex& idx_diff_adaptor_top) const
this is necessary that the type of `idx_diff_adaptor_top` could be not only `AdaptorTopIndex` (which is array of number), but also can accept sequence. I think what makes confusion is the API design at the beginning not properly documented (which is hard for me to control), but here changing the type should be straight forward

2024-10-26 04:15 UTC, carlushuang commented on include/ck_tile/core/tensor/tile_window.hpp
> +// Note: this tile window do not support single issue
control the issue time out side instead of loop over inside this structure

2024-10-26 04:16 UTC, carlushuang commented on include/ck_tile/core/tensor/tile_window.hpp
> +    CK_TILE_DEVICE auto load(number<i_access_unsupport_>          = {},
as the name suggested, this is not support for tile_window class for which issue index it need to use. This is opposite to tile_window_linear

2024-10-26 04:17 UTC, carlushuang commented on include/ck_tile/core/tensor/tile_window.hpp
> +                    0 /**/,
zero is linear_offset which only support in `tile_window_linear` structure

2024-10-26 04:18 UTC, carlushuang commented on include/ck_tile/core/tensor/tile_window.hpp
> +              index_t i_access_unsupport_ = -1,
this is used for async load as the name suggested, I have other local OPs use this. As suggested in other PR , I didn't upload other op into this PR

2024-10-26 15:33 UTC, poyenc approved these changes

2024-10-26 15:52 UTC, poyenc commented
Need more time to go through the files..

2024-10-26 15:52 UTC, merged

2024-10-26 15:55 UTC, poyenc commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +void dump_host_tensor_2d(const ck_tile::HostTensor<T>& x)
I think we can add some macro as a switch to turn on/off debug code like this function.

2024-10-26 15:58 UTC, poyenc commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +    double rtol = 1e-3;
I think we can set smaller error first, and enlarge them if needed.

2024-10-26 16:01 UTC, poyenc commented on example/ck_tile/09_topk_softmax/topk_softmax.cpp
> +        .insert("pr_w", "fp32", "output weight data type(currently only fp32 supported now)")
suggest to use `prec_i`/`prec_w` here

2024-10-26 16:08 UTC, poyenc commented on include/ck_tile/host/fill.hpp
> +#include <unordered_set>
need to sort include directives in lexicographic order

2024-10-26 16:15 UTC, poyenc commented on include/ck_tile/host/fill.hpp
> +template<> struct RawIntegerType_<8> { using type = uint64_t;};
I think we can simply use `_BitInt()` to define the traits

```c++
template <index_t NumBytes>
struct get_fixed_width_uint {
   using type = unsigned _BitInt(CHAR_BIT * NumBytes);
};
```

2024-10-26 16:17 UTC, poyenc commented on include/ck_tile/host/fill.hpp
> +    std::optional<uint32_t> seed_{11939};
I think there is no need to specify the default values here if the parametered `FillUniformDistribution_Unique()` can also act like a default constructor.

2024-10-26 16:20 UTC, poyenc commented on include/ck_tile/ops/topk/block/block_topk_stream_2d.hpp
> +// Copyright (c) 2018-2023, Advanced Micro Devices, Inc. All rights reserved.
need to update the year, too.

2024-10-26 16:22 UTC, poyenc commented on include/ck_tile/ops/elementwise/unary_element_wise_operation.hpp
> +#if 0
We can add those type back when we really need them. It's better for remove them now.

2024-10-26 16:22 UTC, poyenc commented on include/ck_tile/ops/elementwise/unary_element_wise_operation.hpp
> +#if 0
please remove unused types.

2024-10-26 16:23 UTC, poyenc commented on include/ck_tile/ops/topk_softmax/pipeline/topk_softmax_warp_per_row_pipeline.hpp
> +#ifndef TOPK_SOFTMAX_USE_RAW_TILE_WINDOW
Can we define this macro in `topk_softmax_warp_per_row_problem.hpp`?

2024-10-26 16:28 UTC, poyenc commented on include/ck_tile/ops/topk_softmax/pipeline/topk_softmax_warp_per_row_policy.hpp
> +        using topk_problem = BlockTopkStream2DProblem<typename Problem::WeightType,
The naming style of local type alias names is in-consistent with the class type aliases.

2024-10-26 16:36 UTC, poyenc commented on include/ck_tile/ops/softmax/block/block_softmax_2d.hpp
> +    CK_TILE_DEVICE decltype(auto) operator()(const DistributedTensor& x, number<dim> = {})
The `decltype(auto)` only make sense if assuming all the function code will be inlined at the caller site. Though it's true for `__device__` functions, I suggest to use auto here.

2024-10-26 16:37 UTC, poyenc commented on include/ck_tile/ops/softmax/block/block_softmax_2d.hpp
> +#define _BLOCK_SOFTMAX_USE_UNPACK2 0
the naming style is different from others. Can we define it in _config.hpp_?