LWPCK-2429: Device grouped GEMM uses Async Memcpy
ROCm/composable_kernel pull request #1695
Opened 2024-11-26 19:53 UTC by rtmadduri

All the device grouped gemm kernels uses async memcpy

2024-11-28 08:59 UTC, aosewski requested changes
Good job! Looks ok. Just one minor comment.

2024-11-28 08:59 UTC, aosewski commented on include/ck/tensor_operation/gpu/device/impl/device_grouped_gemm_softmax_gemm_permute_xdl_cshuffle.hpp
> +// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.
If you haven't changed anything in this file, please revert the copyright year.

2024-11-30 16:19 UTC, illsilin approved these changes

2024-12-02 08:13 UTC, aosewski approved these changes

2024-12-02 08:13 UTC, merged