Add copy assignment op test
ROCm/composable_kernel pull request #1718
Opened 2024-12-04 20:58 UTC by geyyer

2024-12-04 21:10 UTC, andriy-ca requested changes

2024-12-04 21:10 UTC, andriy-ca commented on test/data_type/test_custom_type.cpp
Just to be sure, I would destroy or overwrite `right_vec` somehow after the assignment.

2024-12-04 21:11 UTC, geyyer commented on test/data_type/test_custom_type.cpp
Thanks, good point!

2024-12-05 17:14 UTC, geyyer commented on test/data_type/test_custom_type.cpp
Added overwriting with a vector of 0s in [8f4a46c](https://github.com/ROCm/composable_kernel/pull/1718/commits/8f4a46c111d1c84fe10bb02b472cb96551da2549).

2024-12-05 22:31 UTC, andriy-ca approved these changes
Looks Great!

2024-12-06 15:56 UTC, merged